In [318]:
import numpy as np
import pandas as pd

In [319]:
df = pd.read_csv('Churn Modeling.csv')

In [320]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [321]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [322]:
df['Geography'] = df['Geography'].astype('category')
df['Gender'] = df['Gender'].astype('category')

In [323]:
X = df.drop(['RowNumber','CustomerId','Surname','Exited'],axis = 1)
y = df['Exited'].values

In [324]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [325]:
le = LabelEncoder()
X['Gender']  = le.fit_transform(X['Gender'])

In [326]:
X.head(10)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   
5          645     Spain       1   44       8  113755.78              2   
6          822    France       1   50       7       0.00              2   
7          376   Germany       0   29       4  115046.74              4   
8          501    France       1   44       4  142051.07              2   
9          684    France       1   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [327]:
X = X.values

In [328]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [329]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])],remainder= 'passthrough')
X = np.array(ct.fit_transform(X))

In [330]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [331]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [332]:
from sklearn.preprocessing import StandardScaler

In [333]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

c:\users\pankaj choudhary\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
c:\users\pankaj choudhary\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
c:\users\pankaj choudhary\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [334]:
import keras

In [335]:
ann = keras.models.Sequential()

In [336]:
ann.add(keras.layers.Dense(units = 7, activation = 'relu'))

In [337]:
ann.add(keras.layers.Dense(units = 6, activation = 'relu'))

In [338]:
ann.add(keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [339]:
ann.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [340]:
ann.fit(X_train,y_train,batch_size=32,epochs=40)

Epoch 1/40
8000/8000 [==============================] - 1s 179us/step - loss: 0.5875 - acc: 0.7055
Epoch 2/40
8000/8000 [==============================] - 1s 65us/step - loss: 0.4654 - acc: 0.7957
Epoch 3/40
8000/8000 [==============================] - 1s 69us/step - loss: 0.4378 - acc: 0.7954
Epoch 4/40
8000/8000 [==============================] - 1s 113us/step - loss: 0.4254 - acc: 0.7967
Epoch 5/40
8000/8000 [==============================] - 1s 100us/step - loss: 0.4183 - acc: 0.8065
Epoch 6/40
8000/8000 [==============================] - 1s 70us/step - loss: 0.4123 - acc: 0.8146
Epoch 7/40
8000/8000 [==============================] - 1s 72us/step - loss: 0.4069 - acc: 0.8199
Epoch 8/40
8000/8000 [==============================] - 1s 101us/step - loss: 0.4016 - acc: 0.8219
Epoch 9/40
8000/8000 [==============================] - 1s 75us/step - loss: 0.3958 - acc: 0.8234: 0s - loss: 0.3967 - acc:
Epoch 10/40
8000/8000 [==============================] - 1s 99us/step - loss: 0.3897 - a

In [341]:
y_pred = ann.predict(X_test)


In [343]:
y_pred= y_pred.reshape(2000)
y_pred = pd.Series(y_pred)
y_pred = y_pred.apply(lambda i : 0 if i < 0.5 else 1)

In [344]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1522   73]
 [ 201  204]]


0.863